### ISSUE TITLE
Can't use exclude option without explicit include

### ISSUE THREAD

**Issue by jmuheim** [glebm/i18n-tasks#137]
I don't want i18n-tasks to search for translations in abstract controllers and helpers like `ApplicationHelper`, where I have this method for example:

```
  def default_page_heading(options = {})
    t '.title', options
  end
```

I tried

```
search:
  exclude:
    - '*/application_helper.rb'
```

But this resulted in

```
josh@Macbuech:~/Documents/Work/MuheimWebdesign/base/src (features/accessibility *)$ i18n-tasks unused
/Users/josh/.rvm/gems/ruby-2.1.0@base/gems/i18n-tasks-0.7.13/lib/i18n/tasks/scanners/pattern_scanner.rb:14:in `scan': invalid byte sequence in UTF-8 (ArgumentError)
```

I had to explicitly also add `include` to make it work:

```
search:
  include:
    - '*.rb'
    - '*.html.*'
    - '*.text.*'

  exclude:
    - '*/application_helper.rb'
```

Is this expected behaviour?
