### ISSUE TITLE
Dummy translation

### ISSUE THREAD

**Issue by ylecuyer** [glebm/i18n-tasks#139]
Add a task that would create a locale file full of dummy translation.

For example the black square could be used: http://www.fileformat.info/info/unicode/char/25a0/index.htm

```yaml
---
dummy:
     welcome: ■■■■■■■
```

Objective: spot untranslated text from a page
