### ISSUE TITLE
"was a leaf, now has children (value <- scope conflict)" error

### ISSUE THREAD

**Issue by oniofchaos** [glebm/i18n-tasks#158]
In two of my views, I have keys that go one level deeper than "necessary". I have these for organizational purposes. i18n-tasks gives me this warning because of the keys. It would be great to have the ability to turn these warnings off, because I don't consider this an issue.

```ruby
# app/views/path/to/view

%p= t('.title')
%p= t('.extra.first') # this throws the warning
%p= t('.extra.second')
```

```yaml
path:
  to:
    view:
      title: I am a webpage
      extra: 
        first: 1
        second: 2
```

**Comment by glebm** [comment]
This warning cannot be silenced because such structure causes issues with i18n-tasks and also i18n itself (e.g. it may confuse its caching mechanism if you enable it). I advise you change the structure, e.g. by putting the key under `extra.any`.  If the keys are dependent on some number, it is best to use the standard supported pluralization mechanism.

**Comment by oniofchaos** [comment]
Thank you for the response.

Is `any` a special keyword? Otherwise, I'm not sure how `extra.any` is different from `extra.first`? Maybe I'm not understanding your suggestion.

**Comment by glebm** [comment]
`any` is not special, `extra.first` would work as well.

**Comment by oniofchaos** [comment]
In my case, the key doesn't really make much sense outside of its nested `path.to.view` context. Both `i18n-tasks` and `i18n` work in my codebase with the nested key (except for the warning of course).

**Comment by glebm** [comment]
If you are using completely different views for different locales, have you considered using [localized views](http://guides.rubyonrails.org/i18n.html#localized-views)? The idea behind i18n is that the keys are the same across locales. Could you perhaps post specifically what you are doing?

**Comment by oniofchaos** [comment]
One example is this:

```yaml
layouts:
  fallout_report: 
    percents:
      this_year: "% of total"
      last_year: "% of total, last year"
```
and in `app/views/layouts/fallout_report.html.haml`:
```haml
%table
  %thead
    %th= t('.percents.this_year') # this causes the warning
    %th= t('.percents.last_year')
```
