### ISSUE TITLE
Doesn't work with locale as directory

### ISSUE THREAD

**Issue by Silex** [glebm/i18n-tasks#176]
Hello,

The following structure doesn't seem to work (my `en` locale gets overwritten with the `fr` one):

``` yaml
base_locale: en
locales: [fr]
data:
  read:
    - config/locales/%{locale}/*.yml
  write:
    - ['{:}.*', 'config/locales/%{locale}/\1.yml']
```

Maybe related to #14

This happens when I do `i18n-tasks add-missing`
