### ISSUE TITLE
Preventing `defaults.en.yml` from being split up?

### ISSUE THREAD

**Issue by connorshea** [glebm/i18n-tasks#177]
I'm unsure exactly how to accomplish what I'm attempting to do here. Essentially, I have a file structure like this:

```
├── en
│   ├── activerecord.en.yml
│   ├── collections.en.yml
│   ├── defaults.en.yml
│   ├── devise.en.yml
│   ├── devise_custom.en.yml
│   ├── frontpage.en.yml
│   ├── generic.en.yml
│   ├── images.en.yml
│   ├── layouts.en.yml
│   └── users.en.yml
└── fr
    ├── activerecord.fr.yml
    ├── collections.fr.yml
    ├── defaults.fr.yml
    ├── devise.fr.yml
    ├── devise_custom.fr.yml
    ├── frontpage.fr.yml
    ├── generic.fr.yml
    ├── images.fr.yml
    ├── layouts.fr.yml
    └── users.fr.yml
```

My `i18n-tasks.yml` config includes this:
```yml
data:
  router: pattern_router
  read:
    - 'config/locales/%{locale}/*.yml'
  write:
    - ['{:}.*', 'config/locales/%{locale}/\1.%{locale}.yml']
```

And this works for everything except `defaults.en.yml`/`defaults.fr.yml`, because it has a structure like [this](https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/en.yml), with multiple top-level items in a single file. When running `normalize`, I get `time.en.yml`, `date.en.yml`, etc. Is there any way for me to prevent the strings in `defaults.%{locale}.yml` from being split up into different files while separating everything else?

Thank you for the awesome gem, it's been super useful for me!
