### ISSUE TITLE
ability to change locale_file_path of prefill

### ISSUE THREAD

**Issue by XORwell** [glebm/i18n-tasks#18]
first at all: nice work! helps alot ;)

following scenario:

my i18n-tasks.yml

``` yaml
data:
  paths:
    - 'config/locales/mystuff/%{locale}.yml'
```

now, running i18n:prefill will use [locale_file_path](https://github.com/glebm/i18n-tasks/blob/master/lib/i18n/tasks/base_task.rb#L32) and change the files in `config/locales/`

config/locales/
├── de.yml
├── en.yml
├── mystuff
│   ├── bg.yml
│   ├── de.yml
│   └── en.yml
