### ISSUE TITLE
`i18n-tasks unused` is displaying a lot of *used* items

### ISSUE THREAD

**Issue by lucascaton** [glebm/i18n-tasks#187]
`$ i18n-tasks unused`
```shell
Unused keys (270) | i18n-tasks v0.9.3
+--------+--------------------------+----------+
| Locale | Key                      | Value    |
+--------+--------------------------+----------+
|   en   | accounts.transfer.submit | Transfer |
etc...
```

**Comment by glebm** [comment]
@lucascaton Could you please try master? Thanks

**Comment by lucascaton** [comment]
@glebm got the same result.

```ruby
# Gemfile
gem 'i18n-tasks', require: false, github: 'glebm/i18n-tasks'
```

```ruby
# Gemfile.lock
GIT
  remote: git://github.com/glebm/i18n-tasks.git
  revision: 3d7e71f21b37dca9eda95fd7fcc16e4ace152ce6
```

**Comment by lucascaton** [comment]
`config/i18n-tasks.yml`:

```yaml
base_locale: en

data:
  read:
    - config/locales/**/%{locale}.yml
    - config/locales/**/*.%{locale}.yml

# Ignoring the following keys because they are defined by 'rails-i18n' gem
ignore_missing:
- 'date.formats.*'
- 'number.currency.format.*'

search:
  exclude:
    - app/assets/images
    - app/assets/fonts
```
