### ISSUE TITLE
False positive 

### ISSUE THREAD

**Issue by mockdeep** [glebm/i18n-tasks#196]
We've got translation keys that we loop through, which `i18n-tasks` gives us a false positive warning for:

```haml
- t('about.team').keys.shuffle.each do |person|
  - data = t("about.team.#{person}")
```

results in:

```
i18n-tasks: [WARN] 'about.team' was a leaf, now has children (value <- scope conflict)
```

**Comment by glebm** [comment]
There is currently no way to avoid this.

However, do you need the keys at all? Why not just have an array instead?

```yaml
about:
  team:
  - Alice
  - Bob
```

```slim
= safe_join t('about.team').shuffle, ' '
```

**Comment by mockdeep** [comment]
Ah, okay, I was able to switch it to:

```yml
about:
  team:
    - name: Alice
      position: Engineer
      bio: stuff
```
