### ISSUE TITLE
Terminal Output breaks when using nested locale files

### ISSUE THREAD

**Issue by athix** [glebm/i18n-tasks#201]
Everything works great with one file per locale, but as soon as I attempt to use subdirectories to break up the locale file, the terminal seems to have bizarre terminal output.

```
# Read and write translations.
data:
  read:
    - config/locales/%{locale}.yml
    - config/locales/**/%{locale}.yml
  write:
    - config/locales/%{locale}.yml
    - config/locales/**/%{locale}.yml
```

Can anyone help me figure this out?
