### ISSUE TITLE
ignore_lines keys are not stringified from YAML

### ISSUE THREAD

**Issue by markedmondson** [glebm/i18n-tasks#206]
When using the YML format for scanner configuration like:

```
  scanners:
  - - "::I18n::Tasks::Scanners::PatternWithScopeScanner"
    - exclude:
      - "*.rb"
      ignore_lines:
        opal: ^\s*#(?!\si18n-tasks-use)
        haml: ^\s*-\\s*#(?!\si18n-tasks-use)
        coffee: ^\s*#(?!\si18n-tasks-use)
```

The `ignore_lines` keys are not stringified, therefore when they hit the [pattern scanner](https://github.com/glebm/i18n-tasks/blob/e8db4a195eefd3005f46d2aea6595a5671be8771/lib/i18n/tasks/scanners/pattern_scanner.rb#L51), they're not found.

The fix is as simple as: https://github.com/markedmondson/i18n-tasks/commit/17925c485e5835734d623a45de5f6e4ec5f97ccf
