### ISSUE TITLE
keys ending in "yes" or "no" are seen as "true" and "false" respectively

### ISSUE THREAD

**Issue by NomNomCameron** [glebm/i18n-tasks#214]
this happens when running `i18n-tasks unused -f keys -l en`

for example, if you have a localization like this:

```yml
en:
  top_level:
    child:
      yes: "something"
      no: "something"
```
the task will flag these as unused and will show that these are the keys that are unused:

`en.top_level.child.true`
`en.top_level.child.false`

**Comment by glebm** [comment]
This has nothing to do with i18n-tasks.
In YAML, `yes` and `no` are boolean (http://yaml.org/type/bool.html).
You need to quote these keys if you want strings, e.g.:

```yaml
en:
  top_level:
    child:
      'yes': "something"
      'no': "something"
```
