### ISSUE TITLE
Sets in key pattern matching

### ISSUE THREAD

**Issue by glebm** [glebm/i18n-tasks#22]
Key pattern matching set support

``` yaml
ignore_unused:
  - simple_form.{placeholders, hints, labels}.*
```

It would be cool if `{...}` translated to a group capture, so it can be backreferenced later:

``` yaml
data:
  write:
    - ['{devise, simple_form}.*', 'config/locales/\1.%{locale}.yml']
```

Spaces within sets are stripped. Delimeter is `,`.

We also need a token to match just one i18n namespace, e.g. `:` (if you have a better idea speak up).  An interesting use case is the following configuration:

``` yaml
data:
  write:
    # normalize every namespace to its own file:
    - ['{:}.*', 'config/locales/\1.%{locale}.yml']
    # top level keys, or don't to enforce none
    - 'config/locales/%{locale}.yml'
```
