### ISSUE TITLE
Time format localization not recognized as used

### ISSUE THREAD

**Issue by jeffblake** [glebm/i18n-tasks#220]
```
en.yml

en:
  time:
    formats:
      time_only: "%l:%M%P"
```

view:
`  = "#{l(ticket_tier_level.event.start_date_zoned, format: :time_only)}-#{l(ticket_tier_level.event.end_date_zoned, format: :time_only)}"
`

Running the remove-unused task will cause the `time` key to be removed
