### ISSUE TITLE
YAML variables

### ISSUE THREAD

**Issue by Friend-LGA** [glebm/i18n-tasks#241]
How to use variables?

For example:
```yaml
---
en:
  word1: &word1
    test
  word2: *word1
```
After `i18n-tasks normalize` it will looks like this:
```yaml
---
en:
  word1: test
  word2: test
```
I couldn't find any related options in config file.
