### ISSUE TITLE
Ignore missing keys for a specific language only?

### ISSUE THREAD

**Issue by erikdahlstrand** [glebm/i18n-tasks#246]
Hi,

Thank you for an awesome tool. Is it possible to ignore missing keys for a specific language only.

Something like:

```yaml
ignore_missing:
  all:
    - 'number.currency.format.unit'
  sv:
    - 'subsite.*'
```
