### ISSUE TITLE
Strange key manipulation when running normalize

### ISSUE THREAD

**Issue by stephen-puiszis** [glebm/i18n-tasks#248]
First off, this is a super handy gem and has saved me hours of work. Thank you all for writing it and maintaining it. 

I've been encountering strange behavior when normalizing or translating keys. This smells like a configuration issue to me but I've been through all the docs and what looks like the relevant source files but haven't found anything yet that answers my question. Please excuse me if this is a dumb question but **is there a way to configure `i18n-tasks normalize` to enforce or ignore values with double quoted strings?** I realize there is a difference between how YAML interprets single and double quotes, I'm attempting to solution a simple way to prevent `normalize` from modify locales that shouldn't be modified. 

Example: 

Here `i18n-tasks normalize` is changing from double quotes to two sets of single quotes:
```
- water_3: "ID condizionatore dell'acqua:"
+ water_3: 'ID condizionatore dell''acqua:'
```

Removing double quotes here (assuming default behavior is no quotes): 
```
     dealer_location:
-      not_available: "N/A"
+      not_available: N/A
```

Finally, on a prior run when I found a key that didn't have any double quoted strings around the `N/A` it did this and added spaces around the slash: 
```
     dealer_location:
-      not_available: N/A
+      not_available: N / A
```

Below is what my configuration looks like, I'm using `0.9.15`: 
```yaml
# The "main" locale.
base_locale: en
## All available locales are inferred from the data by default. Alternatively, specify them explicitly:
locales: [it]
## Reporting locale, default: en. Available: en, ru.
# internal_locale: en

# Read and write translations.
data:
  ## Translations are read from the file system. Supported format: YAML, JSON.
  ## Provide a custom adapter:
  # adapter: I18n::Tasks::Data::FileSystem

  # Locale files or `File.find` patterns where translations are read from:
  read:
    ## Default:
    - config/locales/%{locale}.yml
    ## More files:
    - config/locales/**/*.%{locale}.yml
    ## Another gem (replace %#= with %=):
    # - "<%#= %x[bundle show vagrant].chomp %>/templates/locales/%{locale}.yml"

  # Locale files to write new keys to, based on a list of key pattern => file rules. Matched from top to bottom:
  # `i18n-tasks normalize -p` will force move the keys according to these rules
  write:
    ## For example, write devise and simple form keys to their respective files:
    - ['{simple_form, js}.*', 'config/locales/\1.%{locale}.yml']
    ## Catch-all default:
    - config/locales/%{locale}.yml

  ## Specify the router (see Readme for details). Valid values: conservative_router, pattern_router, or a custom class.
  router: conservative_router
```
