### ISSUE TITLE
Plural keys not recognized

### ISSUE THREAD

**Issue by theodorton** [glebm/i18n-tasks#257]
Given the following template:

```slim
h2.text-center = t('reviews.index.title', count: @reviews.count)
```

or:

```slim
h2.text-center = t('.title', count: @reviews.count)
```

Slim reports missing keys:

```
Unused keys (6) | i18n-tasks v0.9.16
+--------+---------------------------+----------------------+
| Locale | Key                       | Value                |
+--------+---------------------------+----------------------+
|   en   | reviews.index.title.none  | No reviews           |
|   en   | reviews.index.title.one   | One review           |
|   en   | reviews.index.title.other | %{count} reviews     |
|   nb   | reviews.index.title.none  | Ingen anmeldelser    |
|   nb   | reviews.index.title.one   | Én anmeldelse        |
|   nb   | reviews.index.title.other | %{count} anmeldelser |
+--------+---------------------------+----------------------+
```

Although the keys are unused:

```yml
en:
  reviews:
    index:
      title:
        none: No reviews
        one: One review
        other: '%{count} reviews'
```

I'm using `i18n-tasks` version `0.9.16`.

*Edit* Seems the keys are reported as unused not missing.
