### ISSUE TITLE
On Travis CI, getting failure: Failure/Error: raise Parser::SyntaxError, diagnostic

### ISSUE THREAD

**Issue by jmuheim** [glebm/i18n-tasks#261]
Locally, all specs run perfectly.

When on Travis CI, I get the following error:

```
  2) I18n does not have missing keys
     Failure/Error: raise Parser::SyntaxError, diagnostic
     
     I18n::Tasks::CommandError:
       Error scanning vendor/bundle/ruby/2.2.0/gems/activejob-5.0.3/lib/rails/generators/job/templates/job.rb: unterminated string meets end of file
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/parser-2.4.0.0/lib/parser/diagnostic/engine.rb:71:in `process'
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/parser-2.4.0.0/lib/parser/lexer.rb:21608:in `diagnostic'
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/parser-2.4.0.0/lib/parser/lexer.rb:11426:in `advance'
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/parser-2.4.0.0/lib/parser/base.rb:231:in `next_token'
     # /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
     # /home/travis/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/parser-2.4.0.0/lib/parser/base.rb:162:in `parse'
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/parser-2.4.0.0/lib/parser/base.rb:179:in `parse_with_comments'
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/i18n-tasks-0.9.15/lib/i18n/tasks/scanners/ruby_ast_scanner.rb:36:in `scan_file'
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/i18n-tasks-0.9.15/lib/i18n/tasks/scanners/file_scanner.rb:26:in `block in keys'
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/i18n-tasks-0.9.15/lib/i18n/tasks/scanners/files/file_finder.rb:29:in `block in traverse_files'
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/i18n-tasks-0.9.15/lib/i18n/tasks/scanners/files/file_finder.rb:29:in `map'
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/i18n-tasks-0.9.15/lib/i18n/tasks/scanners/files/file_finder.rb:29:in `traverse_files'
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/i18n-tasks-0.9.15/lib/i18n/tasks/scanners/files/caching_file_finder.rb:25:in `traverse_files'
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/i18n-tasks-0.9.15/lib/i18n/tasks/scanners/file_scanner.rb:56:in `traverse_files'
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/i18n-tasks-0.9.15/lib/i18n/tasks/scanners/file_scanner.rb:25:in `keys'
     # /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/i18n-tasks-0.9.15/lib/i18n/tasks/scanners/scanner_multiplexer.rb:32:in `block (3 levels) in collect_results'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
     # ------------------
     # --- Caused by: ---
     # Parser::SyntaxError:
     #   unterminated string meets end of file
     #   /home/travis/build/jmuheim/base/vendor/bundle/ruby/2.2.0/gems/parser-2.4.0.0/lib/parser/diagnostic/engine.rb:71:in `process'
```

It's because of the following spec:

```ruby
require 'i18n/tasks'

RSpec.describe 'I18n' do
  let(:i18n) { I18n::Tasks::BaseTask.new }
  let(:missing_keys) { i18n.missing_keys }
  let(:unused_keys) { i18n.unused_keys }

  it 'does not have missing keys' do
    expect(missing_keys).to be_empty,
      "Missing #{missing_keys.leaves.count} i18n keys, run `i18n-tasks missing' to show them"
  end
end
```

Here's the failing build: https://travis-ci.org/jmuheim/base/jobs/275896526

Any idea? Seems to be some parser problem...?

What's suspicious to me: I tell Travis to use Ruby 2.2.6:

```
rvm:
  - 2.2.6
```

But the file paths (`...vendor/bundle/ruby/2.2.0/gems...`) seem to use 2.2.0.

**Comment by glebm** [comment]
Looks like it's scanning `vendor/bundle`:

>       Error scanning vendor/bundle/ruby/2.2.0/gems/activejob-5.0.3/lib/rails/generators/job/templates/job.rb: unterminated string meets end of file

You can easily avoid that by setting `bundler_args` in `travis.yml` to place the gems outside of your project directory:

```
bundler_args: --path ../../vendor/bundle
```

> But the file paths (...vendor/bundle/ruby/2.2.0/gems...) seem to use 2.2.0.

That's normal, the version there only changes when there are syntax changes in Ruby.

**Comment by glebm** [comment]
Actually, `vendor/bundle` is not scanned by default, so it's likely a problem with your config. Are you trying to scan the entire `vendor/bundle`?

**Comment by glebm** [comment]
I've also opened an issue with Rails to rename those files https://github.com/rails/rails/issues/30690

**Comment by jmuheim** [comment]
Here is my `.travis.yml`:

```yml

dist: trusty
language: ruby
rvm:
  - 2.4.1
bundler_args: --without development
cache: bundler
addons:
  apt_packages:
    - pandoc
  code_climate:
    repo_token: 243e5ab59244b7a1d3fb97d56bfe9961307ad558cb4a7cbeec3c85104e9ee11b
before_install:
  - export TZ=Europe/Zurich
before_script:
  - cp config/secrets.travis.yml config/secrets.yml
script:
  - RAILS_ENV=test bundle exec rails db:create
  - RAILS_ENV=test bundle exec rails db:migrate
  -                bundle exec rails spec
notifications:
  email:
    recipients:
      - joshua.muheim@access-for-all.ch
    on_failure: change
    on_success: change
```

https://github.com/jmuheim/base/blob/master/.travis.yml

I don't see anything suspicious...?
