### ISSUE TITLE
exclude not working for missing

### ISSUE THREAD

**Issue by neohunter** [glebm/i18n-tasks#272]
I've this on my `exclude` settings:

```
  exclude:
  - app/views/beta/**/*
```

However when I run `i18n-tasks missing` I get entries on files that are in the exclude path:

```
| Locale | Key                               | Value in other locales or source                              |
+--------+-----------------------------------+---------------------------------------------------------------+
|  all   | text_1                          | app/views/beta/pages/a.html.erb:19             |
|  all   | text_2                      | app/views/beta/pages/b.html.erb:6                     |
|  all   | text_3                        | app/views/beta/pages/c.html.erb:11
```

I've tried with multiple variations like:

```
  - app/views/beta/*
  - app/views/beta/**
  - app/views/beta
```

But its always the same result.

**Comment by glebm** [comment]
What is the output of `i18n-tasks config`? You may have to quote the values with `*` in yaml.

**Comment by neohunter** [comment]
The output is ok.

```
i18n-tasks config                                                                                        master ✭
internal_locale: en
base_locale: en
locales:
- en
- cs
- de
- es
- fr
- it
- ja
- ko
- zh
data:
  adapter: I18n::Tasks::Data::FileSystem
  read:
  - config/locales/%{locale}/*.yml
  write:
  - config/locales/%{locale}.yml
  yaml:
    write:
      line_width: -1
  search:
  - app/views/admin/requests/invoice.html.erb
  exclude:
  - app/assets/images
  - app/assets/fonts
  - app/assets/videos
  - app/views/admin
  - app/views/beta/**/*
  - app/views/layouts/admin.html.haml
  - app/views/layouts/public_beta.html.erb
search:
  paths:
  - app/
  relative_roots:
  - app/controllers
  - app/helpers
  - app/mailers
  - app/presenters
  - app/views
  scanners:
  - - "::I18n::Tasks::Scanners::RubyAstScanner"
    - only:
      - "*.rb"
  - - "::I18n::Tasks::Scanners::PatternWithScopeScanner"
    - exclude:
      - "*.rb"
  strict: true
translation:
  api_key: xxx
ignore:
- defaults.*
- date.*
- time.*
```

As I said i'd tried with different variations for the exclude options, but always got results from files in the beta folder.
