### ISSUE TITLE
normalize convert emoji characters into unicode 

### ISSUE THREAD

**Issue by neumayr** [glebm/i18n-tasks#291]
Hey!  🙌 

I've spotted that `i18n-tasks normalize` converts emoji characters into unicode which makes them much harder to read and change afterward. IMHO, this should be necessary because `yaml` is capable to understand plain emoji chars. What do you think about this one?

##### Before
```yml
lang:
  de-de: 🇩🇪 German
  en-uk: 🇺🇸 English
  header: 🌐 Select Language
```

##### After `i18n-tasks normalize`
```
lang:
  de-de: "\U0001F1E9\U0001F1EA German"
  en-uk: "\U0001F1FA\U0001F1F8 English"
  header: "\U0001F310 Select Language"
```

#### Converter tool
* https://r12a.github.io/app-conversion/
