### ISSUE TITLE
Is it possible to use gem with an engine based rails application?

### ISSUE THREAD

**Issue by apaokin** [glebm/i18n-tasks#293]
Good evening!
Is it possible to use gem with an engine based rails application? Are there good alternatives for engine applications?

**Comment by apaokin** [comment]
I solved this issue. My engines are located in the engines/ directory. My typical view path looks like this: engines/sessions/app/views/sessions/admin/reports/show.html.slim(engine is called sessions). Also, I have some views in app/ directory.
config/i18n-tasks.yml.erb: 
```
base_locale: en
data:
  read:
    - config/locales/%{locale}.yml
    - engines/**/config/locales/*.yml
  write:
  external:
  yaml:
    write:
      line_width: -1
search:
 # specify paths to engines
  paths:
   - app/
   - engines/announcements/
   - engines/authentication/
   - engines/comments/
   - engines/core/
   - engines/face/
   - engines/jd/
   - engines/pack/
   - engines/sessions/
   - engines/statistics/
   - engines/support/
   - engines/wiki/

  ## Root directories for relative keys resolution. I18n-tasks won't recognize "*" paths, so I will redefine this method.
  relative_roots:
    - app/controllers
    - engines/*/app/controllers/
    - app/helpers
    - engines/*/app/helpers/
    - app/mailers
    - engines/*/app/mailers/
    - app/presenters
    - engines/*/app/presenters/
    - app/views
    - engines/*/app/views/
  exclude:
    - app/assets/images
    - app/assets/fonts
    - app/assets/videos
<% require './lib/relative_keys_extension' %>
```

```
/lib/relative_keys_extension.rb
require 'active_support/all'
module RelativeKeysExtension
  extend ActiveSupport::Concern
  def path_root(path, roots)
    new_roots = roots.map do |p|
      File.expand_path(p) + File::SEPARATOR
    end
    roots_with_star, new_roots = new_roots.partition { |root| root.include? '*' }
    roots_with_star.each do |root|
      new_roots += Dir.glob(root)
    end
    new_roots.sort.reverse_each.detect do |root|
      path.start_with?(root)
    end
  end
end
module I18n::Tasks::Scanners
  [RubyAstScanner, PatternScanner, PatternMapper].each do |scanner|
    scanner.prepend RelativeKeysExtension
  end
end
```

Project with this solution used: https://github.com/octoshell/octoshell-v2/tree/master
