### ISSUE TITLE
Incorrectly displaying unused keys

### ISSUE THREAD

**Issue by leewaa** [glebm/i18n-tasks#299]
I have a form object which includes `ActiveModel::Model` and has some attributes.

In my locale I have something like:
```yml
en:
  activemodel:
    errors:
      models:
        my_form_object:
          attributes:
            my_attribute:
              blank: Please fill in this field
```

Well, i18n-tasks lists this as being unused, when in actual fact, it is being used.

**Comment by jnebeker** [comment]
I'm having the same problem with form label helpers:

```yaml
en:
  helpers:
    label:
      model:
        field: Field Label
```

These are incorrectly showing as unused.
