### ISSUE TITLE
Normalization adds newlines sometimes

### ISSUE THREAD

**Issue by PascalPixel** [glebm/i18n-tasks#346]
Given this:
```yml
ar:
  prohibited_item:
    button: hello
    content: |
      Some content that should be on one line
    title: title

```

`i18n-tasks normalize` produces this:
```yml
---
ar:
  prohibited_item:
    button: hello
    content: 'Some content that should be on one line

'
    title: title

```

It does not happen when given this:
```yml
ar:
  prohibited_item:
    button: hello
    content: |-
      Some content that should be on one line
    title: title

```

Which produces this:
```yml
---
ar:
  prohibited_item:
    button: hello
    content: Some content that should be on one line
    title: title

```
