### ISSUE TITLE
Translation usage in ActionView Components is not recognized

### ISSUE THREAD

**Issue by DylanReile** [glebm/i18n-tasks#353]
All translations in AVCs are marked as unused despite Rails displaying them properly.

**Comment by DylanReile** [comment]
Closing because this is achievable through configuration. Here's my `config/i18n-tasks.yml`:

```
data:
  read:
    - config/locales/*.yml
search:
  relative_paths: &relative_paths
    - "app/controllers"
    - "app/guards"
    - "app/helpers"
    - "app/mailers"
    - "app/presenters"
    - "app/push_notifiers"
    - "app/views"
    - "app/sms_senders"
    - "app/services"
    - "app/components"
  paths: *relative_paths
  relative_roots: *relative_paths
```
