### ISSUE TITLE
Allow for shallow resolution of custom relative i18n keys

### ISSUE THREAD

**Issue by pelletencate** [glebm/i18n-tasks#375]
Using the noticed gem, I have the following I18n use:

```ruby
class MyNotice < ApplicationNotification
  deliver_by :twilio, format: :to_twilio

  def to_twilio
    I18n.t('.super_key')
  end
end
```

I18n resolves this key to `notifications.my_notice.super_key

To use it with I18n, I simply added `/app` to the configuration

```yaml
  ## Root directories for relative keys resolution.
  relative_roots:
    - app/components
    - app/controllers
    - app/helpers
    - app/mailers
    - app/views
    - app
```

I18n-tasks thinks this is a controller action, and resolves this key to `notifications.my_notice.to_twilio.super_key` which is not what Rails / I18n itself does.

How do I tell I18n-tasks to ignore the method name here?

**Comment by glebm** [comment]
There is no way to do this currently.

This where i18n-tasks converts the relative key to an absolute one:

https://github.com/glebm/i18n-tasks/blob/2f44e17f1a291508452c5b95a5f13f7de708ee84/lib/i18n/tasks/scanners/ruby_ast_scanner.rb#L83

**Comment by javierm** [comment]
I'm facing a similar issue when using the view_component gem. I'm using relative keys inside component methods, while also avoiding the `_component` suffix in the YAML files. So far I've added `app/components` to `relative_roots` and then used this monkey-patch.

Do you know whether there's a better way to do this? :thinking: Thanks!

```ruby
if defined?(I18n::Tasks)
  module I18n
    module Tasks
      module Scanners
        module RelativeKeys
          alias_method :original_prefix, :prefix

          def prefix(normalized_path, calling_method: nil)
            if normalized_path.match?(/_component/)
              original_prefix(normalized_path.gsub("_component", ""), calling_method: nil)
            else
              original_prefix(normalized_path, calling_method: calling_method)
            end
          end
        end
      end
    end
  end
end
```

**Comment by glebm** [comment]
There is no way to do this currently other than by monkey patching like above, PR welcome

**Comment by ryanb** [comment]
Instead of the monkey patch for `view_component`, I used this config setting.

```
  # This overrides the default scanners since we need to exclude app/components from RubyAstScanner
  scanners:
  - - "::I18n::Tasks::Scanners::RubyAstScanner"
    - only:
      - "*.rb"
      exclude:
      - "app/components/*.rb"
  - - "::I18n::Tasks::Scanners::PatternWithScopeScanner"
    - exclude:
      - "*.rb"
  - - "::I18n::Tasks::Scanners::PatternWithScopeScanner"
    - only:
      - "app/components/*.rb"
```

It would be nice to have more control over the relative path per directory in i18n-tasks.
