### ISSUE TITLE
Support for multiline string?

### ISSUE THREAD

**Issue by james-em** [glebm/i18n-tasks#383]
Hi,

Sorry in advance if it was already asked. I was wondering if there was a way to prevent this behavior:

```
en:
  admin_mailer:
    profile_approve_email:
      email: >
        <p>Hi</p>
        <p>a new profile is now available to be approved <a href="%{url}">here</a></p>
```

to become

```
en:
  admin_mailer:
    profile_approve_email:
      email: '<p>Hi</p> <p>a new profile is now available to be approved <a href="%{url}">here</a></p>

        '
```

![Screen Shot 2021-06-22 at 12 02 16 PM](https://user-images.githubusercontent.com/63726983/122960717-b0fb4100-d351-11eb-8341-63d4fae08e7b.png)

Thank you !

**Comment by cooljl31** [comment]
Hi! I'm having the same problem running the `i18n-tasks normalize`.

```
-        unsupported_endorsement_type: "Für den Zusatzservice DHL Endorsement wird ein unterstützter 'handling' Wert benötigt. Unterstützte Werte sind: %{supported_values}"
+        unsupported_endorsement_type: 'Für den Zusatzservice DHL Endorsement wird ein unterstützter ' 'handling' ' Wert benötigt. Unterstützte Werte sind: %{supported_values}'
```

I think for that we need an option to disable the conversion `" => '`

**Comment by davidwessman** [comment]
@james-em 

Does it work if you change to use the pipe-operator instead?
```yaml
en:
  admin_mailer:
    profile_approve_email:
      email: |
        <p>Hi</p>
        <p>a new profile is now available to be approved <a href="%{url}">here</a></p>
```

If I do `YAML.load(File.read("./james_example.xml"))` the new lines are already gone, but if I use `|` instead of `>` it works better.
