### ISSUE TITLE
Confusing README for config

### ISSUE THREAD

**Issue by PikachuEXE** [glebm/i18n-tasks#43]
I see this in README:

``` yaml
# config/i18n-tasks.yml
base_locale: en
locales: [es, fr]
```

Does `locales` need to include `base_locale`?
