### ISSUE TITLE
False positive with `default` localization format

### ISSUE THREAD

**Issue by mockdeep** [glebm/i18n-tasks#481]
When we have a `default` localization format we can use it without needing to pass the key:

```yml
en:
  time:
    formats:
      default: '%m/%d/%Y %-I:%M%P %Z'
```

Then:

```rb
l(record.created_at)
```

However, `i18n-tasks` reports this as an unused key.
