### ISSUE TITLE
For mailers: default_i18n_subject is reporting as missing

### ISSUE THREAD

**Issue by mhenrixon** [glebm/i18n-tasks#500]
```ruby
class UserMailer < ApplicationMailer
  def email_verification
    @user       = params[:user]
    @locale     = @user.locale

    I18n.with_locale(@locale) do
      mail to: @user.email, subject: default_i18n_subject
    end
  end

  def invitation_instructions
    @user       = params[:user]
    @locale     = @user.locale

    I18n.with_locale(@locale) do
      mail to: @user.email, subject: default_i18n_subject
    end
  end

  def password_reset
    @user       = params[:user]
    @locale     = @user.locale

    I18n.with_locale(@locale) do
      mail to: @user.email, subject: default_i18n_subject
    end
  end

  def passwordless
    @user       = params[:user]
    @locale     = @user.locale

    I18n.with_locale(@locale) do
      mail to: @user.email, subject: default_i18n_subject
    end
  end
end
```

```yml
en:
  user_mailer:
    email_verification:
      subject: Verify your email
    invitation_instructions:
      subject: Invitation instructions
    password_reset:
      subject: Reset your password
    passwordless:
      subject: Your sign in link
```

I was expecting the task to pick up on the subject here?
