### ISSUE TITLE
`other` sub-key in translation may cause a key to be marked as unused

### ISSUE THREAD

**Issue by ClearlyClaire** [glebm/i18n-tasks#516]
I'm running into an issue similar to #473, but with the `unused` check.

This occurs when a source item has an `other`, and a translation is partial and has only the `other` key:

`en.yml`:
```yml
---
en:
  preferences:
    other: Other
    posting_defaults: Posting defaults
```

`ga.yml`:
```yml
---
ga:
  preferences:
    other: Eile
```

This causes `i18n-tasks unused` to incorrectly flag the translation as unused:
```
Unused keys (58) | i18n-tasks v1.0.12
+--------+-------------+--------------------+
| Locale | Key         | Value              |
+--------+-------------+--------------------+
|   ga   | preferences | {"other"=>"Eile"}  |
+--------+-------------+--------------------+
```

Adding `'preferences.other'` to `ignore_unused` works, but it would be preferable if `i18n-tasks` could detect this is not a plural key based on use or reference locale, or failing that, have an option to mark known keys as non-plural, but not preventing the unused key check if they truly get unused at some point.
