### ISSUE TITLE
`i18n-tasks missing` ignores YAML aliases and anchors

### ISSUE THREAD

**Issue by jared-thoughtbot** [glebm/i18n-tasks#517]
We have an app that is mostly in English, but there are a few keys that we want to have in multiple languages.

```yaml
# en.yml
en:
  hello: "Hello world"
  most: "other"
  text: "we only need in English"

# pt.yml
pt:
  hello: "Olá Mundo"
```

Running `i18n-tasks missing` tells us we have missing translations (which we do!). First we tried to solve this by simply copying all the missing key/values into each language file.

```yaml
# en.yml
en:
  hello: "Hello world"
  most: "other"
  text: "we only need in English"

# pt.yml
pt:
  hello: "Olá Mundo"
  most: "other"
  text: "we only need in English"
```

This works, but as we work on the app and add another translation (just in English), we keep hitting the "Missing Translations" warning.

```yaml
# en.yml
en:
  hello: "Hello world"
  most: "other"
  text: "we only need in English"
  new: "text only in English"

# pt.yml
pt:
  hello: "Olá Mundo"
  most: "other"
  text: "we only need in English"
```

We thought we could be clever and take advantage of YAML [Aliases and Anchors](https://stackoverflow.com/questions/6651275/what-do-the-mean-in-this-database-yml-file/6651436#6651436). We combined all the files together (because most of it's in English anyway)

```yaml
# locales.yml
en: &default
  hello: "Hello world"
  most: "other"
  text: "we only need in English"
  new: "text only in English"

pt:
  <<: *default
  hello: "Olá Mundo"
```

Rails is happy with this but `i18n-tasks missing` still complains saying `Missing translations`.

I appreciate this is a pretty niche use case, but I wanted to ask if this is expected or whether the `missing` check should respect YAML aliases and anchors?

**Comment by jared-thoughtbot** [comment]
@glebm or @davidwessman hi there! :) Just wondered if you had any thoughts here?

**Comment by davidwessman** [comment]
@jared-thoughtbot I tried to investigate this and wrote some tests for it.
Could you share how your `i18n-tasks` looks? Especially the `data/read` `data/write` looks?

**Comment by davidwessman** [comment]
With config:
```yaml
---
:base_locale: en
:locales:
- en
- pt
:data:
  :read:
  - config/locales/anchors.yml
```

I get it to use the alias from the translation, but it will not work with i18n-tasks writing any keys.

**Comment by jared-thoughtbot** [comment]
@davidwessman you were spot on with the config and the `data/read`.

Our config didn't have anything for data read or write, so it was falling back to the default of `config/locales/%{locale}.yml`. But I'd renamed the combined local yaml to `config/locales/locales.yml` 🤦 

Updating `config/i18n-tasks.yml` to include

```yaml
data:
  read:
    - config/locales/locales.yml
```

solved it. Thank you for investigating this, I really appreciate it!
