### ISSUE TITLE
Google Translate removes newlines

### ISSUE THREAD

**Issue by davidwessman** [glebm/i18n-tasks#566]
I'm using the pipe-operator, and the multi-lines are also concatenated into a single one (without space: `…</p><p>…`) on the target locale when I run e.g. `i18n-tasks translate-missing`.

[Edited] Example:

```yaml
# config/locales/en.yml
en:
  intro_html: |
    <p>Hello</p>
    <p>World</p>
```

```bash
# Translate with Google
i18n-tasks translate-missing -l fr
```

```yaml
# config/locales/fr.yml
fr:
  intro_html: "<p>Bonjour</p><p>Monde</p>"
```

(with i18n-tasks 1.0.12)

_Originally posted by @otagi in https://github.com/glebm/i18n-tasks/issues/383#issuecomment-1268418987_
