### ISSUE TITLE
Normalize moves empty string keys to a new file

### ISSUE THREAD

**Issue by jaredmoody** [glebm/i18n-tasks#579]
To translate a blank option in a select in simple form, I have a key that is an empty string:

```
# config/locales/en_US/projects/tax_options.yml
en_US:
  simple_form:
    options:
      project:
        tax_labor:
          '': Use product default
          'false': Do not tax labor on all items
          'true': Tax labor on all items
```

Normalize is pulling out only the blank key and adding it to a new file at `config/locales/en_US/en_US.yml`, which I don't want.

I think this is a bug because AFAIU the conservative router is not supposed to move keys, correct?
