### ISSUE TITLE
Feature: Translation of few/many keys based on the locale

### ISSUE THREAD

**Issue by marselmustafin** [glebm/i18n-tasks#582]
I have such keys in my base `en` locale:
```
    friends:
      one: one friend
      other: "${count} friends"
      zero: no friends
```

When I translate it to other languages with `translate-missing` I have the same keys everywhere. E.g. in Russian:
```
    friends:
      one: один друг
      other: "%{count} друзей"
      zero: нет друзей
```

But I would like to have more values included in locales that require more pluralization keys, expected result for Russian:

```
    friends:
      one: один друг
      few: "%{count} друга"
      many: "%{count} друзей"
      other: "%{count} друзей"
      zero: нет друзей
```

Is it possible to achieve this result currently? Or it requires additional feature implementation?
