### ISSUE TITLE
i18n-tasks missing returning all keys present (false positive?)

### ISSUE THREAD

**Issue by nflorentin** [glebm/i18n-tasks#584]
Hi,

Just installed i18n-tasks. `unused` command is working fine but `missing` command is not.

Here is my config file:
```YML
base_locale: fr
locales: [en, es]
data:
  read:
    - config/locales/**/[!ice_cube]*.%{locale}.yml
  write:
  external:
  yaml:
    write:
      line_width: -1
search:
  relative_roots:
    - app/controllers
    - app/helpers
    - app/mailers
    - app/presenters
    - app/views
    - app/views/mailers
    - app/services
  exclude:
    - app/assets/images
    - app/assets/fonts
    - app/assets/videos
    - app/assets/builds
  ast_matchers:
    - 'I18n::Tasks::Scanners::AstMatchers::DefaultI18nSubjectMatcher'
ignore_unused:
  - 'errors.*'
  - 'activerecord.models.*'
  - 'activerecord.attributes.*'
  - 'activerecord.errors.models.*'
  - 'activerecord.errors.messages.*'
  - 'activemodel.*'
  - 'number.*'
  - 'helpers.*'
  - 'time.*'
  - 'datetime.*'
  - 'date.*'
  - 'attributes.*'
  - 'support.array.*'
  - 'devise.*'
  - 'services.*'
  - '{true,false}'
ignore:
  - ice_cube.*
```

Here is the result of command `i18n-tasks unused`, returning almost all keys (my test suite is passing and all keys are present):
```bash
+--------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------+
| Locale | Key                                                                                                | Value in other locales or source                                          |
+--------+----------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------+|
|  all   | admin.auth_provider_config_saml.fields.info_for_idp_config                                         | app/views/admin/auth_provider_config_saml/_fields.html.erb:4              |
|  all   | admin.auth_provider_config_saml.fields.metadata_xml                                                | app/views/admin/auth_provider_config_saml/_fields.html.erb:6              |
|  all   | admin.banners.form.active_hint                                                                     | app/views/admin/banners/_form.html.erb:5                                  |
|  all   | admin.banners.form.content_hint                                                                    | app/views/admin/banners/_form.html.erb:16                                 |
|  all   | admin.categories.edit.title                                                                        | app/views/admin/categories/edit.html.erb:4                                |
|  all   | admin.categories.index.new                                                                         | app/views/admin/categories/_index.html.erb:26                             |
|  all   | admin.categories.new.title                                                                         | app/views/admin/categories/new.html.erb:4                                 |
|  all   | admin.conditions.nested_form.booking_allowed_to_members_whose                                      | app/views/admin/conditions/_nested_form.html.erb:48                       |
|  all   | admin.conditions.nested_form.or                                                                    | app/views/admin/conditions/_nested_form.html.erb:7                        |
|  all   | admin.custom_fields.edit.title                                                                     | app/views/admin/custom_fields/edit.html.erb:4                             |
|  all   | admin.custom_fields.index.new                                                                      | app/views/admin/custom_fields/_index.html.erb:28                          |
|  all   | admin.custom_fields.new.title                                                                      | app/views/admin/custom_fields/new.html.erb:4                              |
|  all   | admin.doc_numberings.edit.title                                                                    | app/views/admin/doc_numberings/edit.html.erb:4                            |
|  all   | admin.groups.destroy_confirmation.replacement_group                                                | app/views/admin/groups/destroy_confirmation.html.erb:9                    |
|  all   | admin.groups.edit.title                                                                            | app/views/admin/groups/edit.html.erb:4                                    |
|  all   | admin.groups.form.supporting_doc_types_subtitle                                                    | app/views/admin/groups/_form.html.erb:18                                  |
|  all   | admin.groups.new.title                                                                             | app/views/admin/groups/new.html.erb:4                                     |
|  all   | admin.machine_sheets.conditions_form.define_booking_conditions                                     | app/views/admin/machine_sheets/_conditions_form.html.erb:43               |
|  all   | admin.machine_sheets.conditions_form.define_booking_conditions_tooltip                             | app/views/admin/machine_sheets/_conditions_form.html.erb:44               |
|  all   | admin.machine_sheets.conditions_form.hours_per_day                                                 | app/views/admin/machine_sheets/_conditions_form.html.erb:36               |
|  all   | admin.machine_sheets.edit.add_media                                                                | app/views/admin/machine_sheets/edit.html.erb:129                          |
|  all   | admin.machine_sheets.edit.define_main_image                                                        | app/views/admin/machine_sheets/edit.html.erb:74                           |
... 260 missing keys in total
```

I investigate for hours, I still don't understand why there are so many false positive.

Ex: first result of the command: `admin.auth_provider_config_saml.fields.info_for_idp_config`
In file `app/views/admin/auth_provider_config_saml/_fields.html.erb`:
```ERB
<%= t(".info_for_idp_config") %>
```
Translation is present:
```ruby
3.3.2 :001 > I18n.t("admin.auth_provider_config_saml.fields.info_for_idp_config")
 => "Informations pour configurer votre IdP"
```

Am I missing something ?
Thanks in advance...!

**Ruby version: 3.3.2
Rails version: 7.1.3.3
i18n-taks version: 1.0.4**
