### ISSUE TITLE
Add ollama as backend translation service

### ISSUE THREAD

**Issue by guillaumebriday** [glebm/i18n-tasks#591]
That would be great to be able to run translation service locally like https://github.com/ollama/ollama

The implementation would be really close to the openai one: https://github.com/glebm/i18n-tasks/blob/main/lib/i18n/tasks/translators/openai_translator.rb

I could open a PR if you think it's worth it

Thank you in advance

**Comment by glebm** [comment]
Sure, the more backends the better :+1:

**Comment by zealot128** [comment]
I also wanted to use a different OpenAI compat service (those are usually like 80% cheaper than OpenAI). Monkey patched it like this:


```ruby
# lib/deep_seek_translator.rb
# frozen_string_literal: true

# Patch OpenAI translator to use DeepSeek API (OpenAI-compatible)
require "i18n/tasks/translators/openai_translator"

module I18n::Tasks::Translators
  class OpenAiTranslator
    private

    def translator
      @translator ||= begin
        config = @i18n_tasks.translation_config
        opts = { access_token: api_key, log_errors: true }
        opts[:uri_base] = config[:openai_base_uri] if config[:openai_base_uri].present?
        OpenAI::Client.new(**opts)
      end
    end
  end
end
```

Require in i18n-tasks.yml:

```yaml
<% require File.join(Dir.pwd, 'lib/deepseek_translator') %>

translation:
  backend: openai
  openai_api_key: <%= ENV['DEEPSEEK_API_KEY'] %>
  openai_base_uri: https://api.deepseek.com
  openai_model: deepseek-chat
```

seemed to do the trick!
