### ISSUE TITLE
Newline placeholder `<br id=i18n />` is not replaced with newline after translation

### ISSUE THREAD

**Issue by paulwalk** [glebm/i18n-tasks#595]
I am finding the `<br id=i18n />` in my translated locales. I understand from this [recent commit](https://github.com/glebm/i18n-tasks/commit/7bf71a56023078ee1496e5baac1ae16f14992211) that:

> - Line breaks are not kept when translating html content via Google Translate
> - Therefore we transform `\n` into a placeholder and then back after
  translating
> - Fixes https://github.com/glebm/i18n-tasks/issues/566

 It is the "and then back after translating" part which does not seem to be working.

**Comment by davidwessman** [comment]
> I am finding the `<br id=i18n />` in my translated locales. I understand from this [recent commit](https://github.com/glebm/i18n-tasks/commit/7bf71a56023078ee1496e5baac1ae16f14992211) that:
> 
> 
> 
> > - Line breaks are not kept when translating html content via Google Translate
> 
> > - Therefore we transform `\n` into a placeholder and then back after
> 
>   translating
> 
> > - Fixes https://github.com/glebm/i18n-tasks/issues/566
> 
> 
> 
>  It is the "and then back after translating" part which does not seem to be working.

Could you try to write a test case which triggers it? Or try edit existing tests?

**Comment by paulwalk** [comment]
I'm afraid that I'm not competent to write a unit test for this, but I can offer an example that fails:

**`en.yml`**
```yaml
---
en:
  test_html_translation:
    some_html: |-
      <p>Each repository in this directory is characterised by the following features:</p>
      <ul>
        <li>The majority of its content is fully Open Access</li>
        <li>It has a functioning OAI-PMH interface</li>
      </ul>
```

Running `i18n-tasks translate-missing` generates the following file (Spanish example):

**`es.yml`**
```yaml
---
es:
  test_html_translation:
    some_html: "<p>Cada repositorio de este directorio se caracteriza por las siguientes características:</p><br id=i18n /><ul><br id=i18n /><li> La mayor parte de su contenido es totalmente de acceso abierto.</li><br id=i18n /><li> Tiene una interfaz OAI-PMH funcional</li><br id=i18n /></ul>"
```
