### ISSUE TITLE
Error running i18n-tasks add-missing base

### ISSUE THREAD

**Issue by timvoet** [glebm/i18n-tasks#60]
I am receiving this error when trying to add missing messages to the base locale

```
$i18n-tasks  add-missing base
/Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.3.11/lib/i18n/tasks/data/locale_tree.rb:79:in `[]=': string not matched (IndexError)
    from /Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.3.11/lib/i18n/tasks/data/locale_tree.rb:79:in `block in list_to_tree_data'
    from /Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.3.11/lib/i18n/tasks/data/locale_tree.rb:74:in `each'
    from /Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.3.11/lib/i18n/tasks/data/locale_tree.rb:74:in `list_to_tree_data'
    from /Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.3.11/lib/i18n/tasks/data/locale_tree.rb:63:in `to_tree_data'
    from /Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.3.11/lib/i18n/tasks/data/locale_tree.rb:55:in `to_tree_data'
    from /Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.3.11/lib/i18n/tasks/data/locale_tree.rb:13:in `merge'
    from /Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.3.11/lib/i18n/tasks/data.rb:75:in `update_locale_data'
    from /Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.3.11/lib/i18n/tasks/data.rb:50:in `block in update_data'
    from /Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.3.11/lib/i18n/tasks/data.rb:50:in `each'
    from /Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.3.11/lib/i18n/tasks/data.rb:50:in `update_data'
    from /Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.3.11/lib/i18n/tasks/fill_tasks.rb:7:in `fill_missing_value'
    from /Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.3.11/lib/i18n/tasks/commands.rb:57:in `block in <class:Commands>'
    from /Users/tvoet/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/i18n-tasks-0.3.11/bin/i18n-tasks:45:in `<top (required)>'
    from /Users/tvoet/.rbenv/versions/2.1.0/bin/i18n-tasks:23:in `load'
    from /Users/tvoet/.rbenv/versions/2.1.0/bin/i18n-tasks:23:in `<main>'

```

this is my config config/i18n-tasks.yml

```
base_locale: en
locales: [en, fr]
data:
  yaml:
    write:
      line_width: -1
  # a list of file globs to read from per-locale
  read:
    # read from namespaced files, e.g. simple_form.en.yml
    - 'config/locales/*.%{locale}.yml'
    # read from a gem (config is parsed with ERB first, then YAML)
    #- "<%= %x[bundle show vagrant].chomp %>/templates/locales/%{locale}.yml"
    # default
    - 'config/locales/%{locale}.yml'
  # a list of {key pattern => file} routes, matched top to bottom
  write:
    # write models.* and views.* keys to the respective files
    - ['{models,views}.*', 'config/locales/\1.%{locale}.yml']
    # or, write every top-level key namespace to its own file
    #- ['{:}.*', 'config/locales/\1.%{locale}.yml']
    # default, sugar for ['*', path]
    - 'config/locales/%{locale}.yml'

translation:
  api_key: <my_api_key>
```
