### ISSUE TITLE
Isolating router scrambles multiple files

### ISSUE THREAD

**Issue by gr8bit** [glebm/i18n-tasks#607]
I have some locale files I want to sort but individually, so every file separately. Therefore, I have the following config in `config/i18n-tasks.yml`:
```yaml
base_locale: en
data:
  read:
    - config/locales/%{locale}.yml
    - config/locales/*.%{locale}.yml
    - config_tenants/locales/*.%{locale}.*.yml
  router: isolating_router
```
When I execute
```sh
i18n-tasks normalize
```
it moves translations around in these files, leaving some almost empty and others with most of the translations even from other files. This should not happen as I'm using the `isolating_router`.
Changing the order of the `read` section changes the outcome a little, but it's still wrong in the same way.
