### ISSUE TITLE
"normalize" destroys stuff like &defaults

### ISSUE THREAD

**Issue by jmuheim** [glebm/i18n-tasks#61]
I often use stuff like the following:

```
de:
  activerecord:
    attributes:
      defaults: &defaults
        created_at: 'Erstellt am'
        updated_at: 'Aktualisiert am'
      user:
        <<: *defaults
        current_password: Aktuelles Passwort
```

Sadly, when doing `i18n-tasks normalize`, these are "flattened". Is there any way to circumvent this?
