### ISSUE TITLE
Check for translation of model names and attributes

### ISSUE THREAD

**Issue by jmuheim** [glebm/i18n-tasks#62]
I have written two specs which check for untranslated model names and attributes. Their output looks like this:

![image](https://cloud.githubusercontent.com/assets/1814983/2870125/f1fe9a40-d2ae-11e3-9b9b-c50417ac0dbd.png)

Because you don't want to always translated every model's name and attributes, I added two keys to the `i18n-tasks.yml` file where one can specify exceptions:

```
ignore_untranslated:
  model_names:
    - role
  model_attributes:
    user:
      - encrypted_password
      - reset_password_token
      - reset_password_sent_at
      - remember_created_at
      - unconfirmed_email
      - confirmation_token
      - confirmation_sent_at
      - unlock_token
      - sign_in_count
```

The code is not refactored yet, so I won't post it here at this time. But would you be interested in a wiki page or something about this topic?
