### ISSUE TITLE
missing reports keys as missing despite them existing in locale file (v1.0.15, Decidim module context)

### ISSUE THREAD

**Issue by rafalsty** [glebm/i18n-tasks#628]
**Environment**:

i18n-tasks version: 1.0.15
Ruby version: ruby 3.3.7 (2025-01-15 revision be31f993d7) [x86_64-linux]
Rails version: 7.0.8.4 (From parent Decidim directory)
OS: Ubuntu

**Problem Description**:

When running bundle exec i18n-tasks missing --locales en within a Decidim module's directory (decidim-explicit-voting), it consistently reports 4 specific keys as missing:

decidim.explicit_voting.admin.votings.index.yes
decidim.explicit_voting.admin.votings.index.no
decidim.explicit_voting.votings.show.yes
decidim.explicit_voting.votings.show.no

These keys are used in the corresponding view files (app/views/decidim/explicit_voting/...) via relative keys (t(".yes"), t(".no")).

The keys definitely exist in the config/locales/en.yml file located within the module's directory, at the correct paths.

Running bundle exec i18n-tasks find '<key>' correctly identifies the usage of the key in the view file but does not show the value/definition from the locale file.

**Expected Behavior**:

i18n-tasks missing should report no missing keys for these specific 4 keys in the en locale.
i18n-tasks find should show both the usage (occurrence) and the definition (value) for these keys.

**Configuration** (config/i18n-tasks.yml located in the module directory decidim-explicit-voting/config/):

YAML

```
# ~/git/decidim-explicitvoting/decidim-explicit-voting/config/i18n-tasks.yml

# Base locale
base_locale: en

# Read translations from (relative to module directory)
data:
  read:
    - config/locales/%{locale}.yml # Direct path to locales within the module
  yaml:
    write:
      line_width: -1 # Optional: do not wrap lines

# Search for key usage (relative to module directory)
search:
  paths:
    - app
    - lib
  # Resolve relative keys (e.g., t(".key"))
  relative_roots:
    - app/controllers
    - app/helpers
    - app/mailers
    - app/presenters
    - app/services
    - app/views
    - app/cells
  strict: false # As in the original parent config

# ignore_missing: [] # Copied lists omitted for brevity, but do not include patterns matching the missing keys
# ignore_unused: [] # Copied lists omitted for brevity
```

**Locale File Snippet** (config/locales/en.yml located in the module directory):

YAML

```
en:
  decidim:
    explicit_voting:
      admin:
        votings:
          index:
            # ... other keys ...
            yes: "Yes" # Key exists and is quoted
            no: "No"   # Key exists and is quoted
            # ... other keys ...
      votings:
        show:
          # ... other keys ...
          yes: "Yes" # Key exists and is quoted
          no: "No"   # Key exists and is quoted
          # ... other keys ...
# Ensure the full path matches exactly, including 'decidim' and 'explicit_voting' levels.
# The rest of the file content exists but is omitted for brevity.
```

**Code Snippet** (Example Usage in app/views/decidim/explicit_voting/admin/votings/index.html.erb):

Fragment of the code

```
<td>
  <%= voting.secret? ? t(".yes") : t(".no") %>
</td>
```

**Command Outputs** (run from module directory .../decidim-explicit-voting/):

bundle exec i18n-tasks missing --locales en

> Missing translations (4) | i18n-tasks v1.0.15
> +--------+-------------------------------------------------+-------------------------------------------------------------------+
> | Locale | Key                                             | Value in other locales or source                                  |
> +--------+-------------------------------------------------+-------------------------------------------------------------------+
> |   en   | decidim.explicit_voting.admin.votings.index.no  | app/views/decidim/explicit_voting/admin/votings/index.html.erb:36 |
> |   en   | decidim.explicit_voting.admin.votings.index.yes | app/views/decidim/explicit_voting/admin/votings/index.html.erb:36 |
> |   en   | decidim.explicit_voting.votings.show.no         | app/views/decidim/explicit_voting/votings/show.html.erb:80        |
> |   en   | decidim.explicit_voting.votings.show.yes        | app/views/decidim/explicit_voting/votings/show.html.erb:80        |
> +--------+-------------------------------------------------+-------------------------------------------------------------------+

bundle exec i18n-tasks find 'decidim.explicit_voting.admin.votings.index.yes'

> 1 key matching 'decidim.explicit_voting.admin.votings.index.yes' (1 usage) | i18n-tasks v1.0.15
> decidim.explicit_voting.admin.votings.index.yes
>   app/views/decidim/explicit_voting/admin/votings/index.html.erb:36 <%= voting.secret? ? t(".yes") : t(".no") %>

bundle exec i18n-tasks health

> Forest (en, pl) has 147 keys across 2 locales. On average, values are 17 characters long, keys have 5.3 segments, a locale has 73 keys.
> Missing translations (13) | i18n-tasks v1.0.15
> +--------+--------------------------------------------------------------+-------------------------------------------------------------------+
> | Locale | Key                                                          | Value in other locales or source                                  |
> +--------+--------------------------------------------------------------+-------------------------------------------------------------------+
> |  all   | decidim.explicit_voting.admin.votings.index.no               | app/views/decidim/explicit_voting/admin/votings/index.html.erb:36 | # Still reported missing
> |  all   | decidim.explicit_voting.admin.votings.index.yes              | app/views/decidim/explicit_voting/admin/votings/index.html.erb:36 | # Still reported missing
> |  all   | decidim.explicit_voting.votings.show.no                      | app/views/decidim/explicit_voting/votings/show.html.erb:80        | # Still reported missing
> |  all   | decidim.explicit_voting.votings.show.yes                     | app/views/decidim/explicit_voting/votings/show.html.erb:80        | # Still reported missing
> |   pl   | decidim.explicit_voting.admin.voting_options.create.error    | en There was a problem creating the voting option                 |
> |   pl   | decidim.explicit_voting.admin.voting_options.create.success  | en Voting option was successfully created                         |
> # ... (other missing pl keys) ...
> +--------+--------------------------------------------------------------+-------------------------------------------------------------------+
> Unused keys (38) | i18n-tasks v1.0.15
> +--------+------------------------------------------------------------------+----------------------------------------------------+
> | Locale | Key                                                              | Value                                              |
> +--------+------------------------------------------------------------------+----------------------------------------------------+
> # ... (other unused keys) ...
> |   en   | decidim.explicit_voting.admin.votings.index.false                | No                                                 | # Confusingly reports `.false` as unused
> |   en   | decidim.explicit_voting.admin.votings.index.true                 | Yes                                                | # Confusingly reports `.true` as unused
> |   en   | decidim.explicit_voting.votings.show.false                       | No                                                 | # Confusingly reports `.false` as unused
> |   en   | decidim.explicit_voting.votings.show.true                        | Yes                                                | # Confusingly reports `.true` as unused
> # ... (other unused keys including pl versions of true/false) ...
> +--------+------------------------------------------------------------------+----------------------------------------------------+
> ✓ Perfect! No inconsistent interpolations found.
> The following data requires normalization:
> config/locales/en.yml
> config/locales/pl.yml
> Run `i18n-tasks normalize` to fix

(Note: The health command run from the module directory does read the keys, but still reports the 4 .yes/.no keys as missing. Confusingly, it also reports keys ending in .true/.false as unused, although the locale file contains .yes/.no.)

**Debugging Attempts**:

Confirmed en.yml exists at the correct path (config/locales/en.yml) relative to the execution directory.
Validated en.yml using yamllint (after fixing an initial duplicate key error unrelated to these specific keys). The file should now be syntactically correct.
Checked file encoding; file command reports ASCII text, which is a valid UTF-8 subset.
Initially tried using a shared i18n-tasks.yml from a parent directory, but encountered path resolution issues.
Now using the simplified, local config/i18n-tasks.yml (shown above) within the module directory, running commands from the module root without --config.
Confirmed the read: path in the local config is config/locales/%{locale}.yml.
Tried using --debug and -v flags with i18n-tasks v1.0.15, but these flags do not provide verbose logging output in this version (either "invalid option" or just prints the version number).
