### ISSUE TITLE
ERB config file method throws error

### ISSUE THREAD

**Issue by thomaswitt** [glebm/i18n-tasks#649]
When I install the GEM and create a minimal `config/i18n-tasks.yml.erb`

```
base_locale: en

search:
  exclude:
    - app/assets/builds
    - app/assets/fonts
    - app/assets/images
    - app/assets/tailwind
    - app/assets/videos

  translation:
    openai_api_key: <%= Rails.application.credentials.dig(:openai, :access_token) %>
    openai_model: "gpt-4o-mini" # see https://platform.openai.com/docs/models

```

I immediately get an error

```
❯ bundle exec i18n-tasks health
bundler: failed to load command: i18n-tasks (/Users/thomas/.rbenv/versions/3.4.4/bin/i18n-tasks)
(eval at /Users/thomas/.rbenv/versions/3.4.4/lib/ruby/gems/3.4.0/gems/i18n-tasks-1.0.15/lib/i18n/tasks/configuration.rb:26):5:in 'I18n::Tasks::Configuration#file_config': uninitialized constant I18n::Tasks::Configuration::Rails (NameError)
```

When I copy the default config, everything works. An empty config/i18n-tasks.yml doesn't help either
