### ISSUE TITLE
translate-missing very broken

### ISSUE THREAD

**Issue by pekeler** [glebm/i18n-tasks#67]
input:

```

---
en:
  marker_1: MARKER_1
  works_good: Works good
  problem_1_html: By clicking <strong>Securely Sign up</strong> you agree to the %{tos_link} and %{privacy_link}.
  marker_2: MARKER_2
  n_a: n/a
  n_a_html: n/a
  marker_3: MARKER_3
  S: S
  S_html: S
  marker_4: MARKER_4
```

and

```

---
es:
```

bundle exec i18n-tasks translate-missing -l es -f en

output:

```

---
es:
  marker_1: MARKER_1
  works_good: Funciona bien
  problem_1_html: MARKER_2
  marker_2: n / a
  n_a: MARKER_3
  n_a_html: S
  marker_3: MARKER_4
  S: Al hacer clic en <strong>Ingresar con seguridad hasta</strong> que usted está de acuerdo con el %{tos_link} y %{privacy_link}.
  S_html: n / a
  marker_4: S

```
