### ISSUE TITLE
plurals seem to be ignored

### ISSUE THREAD

**Issue by pekeler** [glebm/i18n-tasks#69]
Input en.yml:

```

---
en:
  stuff: Stuff
  days:
    one: 1 day
    other: "%{count} days"
  more_stuff: More stuff
```

Input es.yml:

```

---
es:
```

`bundle exec i18n-tasks translate-missing -l es -f en`
result es.yml:

```

---
es:
  stuff: Cosas
  more_stuff: Más cosas
```
