### ISSUE TITLE
devise translations reported as missing

### ISSUE THREAD

**Issue by gingerlime** [glebm/i18n-tasks#74]
Scratching my head about this for a couple of hours. Maybe I'm doing something stupid, but I thought I'd ask anyway.

We have translations for devise in `config/locales/devise.(en|de|...).yml`. I've updated the generated config so it looks like this

``` yaml
data:
   :adapter: I18n::Tasks::Data::FileSystem
   :config: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
     read:
      - config/locales/%{locale}.yml
      - config/locales/devise.%{locale}.yml
      write:
      - config/locales/%{locale}.yml
      - config/locales/devise.%{locale}.yml
```

For some reason I get the devise translations reported missing, even though they are working fine.

Did I miss anything??
