### ISSUE TITLE
"Unused" doesn't work

### ISSUE THREAD

**Issue by khelal** [glebm/i18n-tasks#75]
Given this config file:

```
base_locale: en
locales: [en, ar, fr]
data:
  adapter: I18n::Tasks::Data::FileSystem
  read:
  - config/locales/*/*%{locale}.yml
  write:
  - config/locales/%{locale}.yml
relative_roots:
- app/controllers
- app/helpers
- app/views
search:
  scanner: I18n::Tasks::Scanners::PatternWithScopeScanner
  relative_roots:
  - app/
  paths:
  - app
  exclude:
  - "*.jpg"
  - "*.png"
  - "*.gif"
  - "*.svg"
  - "*.ico"
  - "*.eot"
  - "*.ttf"
  - "*.woff"
  - "*.pdf"
  ignore_lines:
  - "^\\s*[#/](?!\\si18n-tasks-use)"

```

When i run "bundle exec i18n-tasks unused" it tells me that I have 0 unused strings, altho I know for a fact that this is not right as I added a couple of random strings in there.
