### ISSUE TITLE
grep exclude pattern

### ISSUE THREAD

**Issue by dmke** [glebm/i18n-tasks#8]
I have a bunch of Javascript assets (`app/assets/javascripts/*.js*`) which make use of `t()` calls, and will therefore be found by grep, although they're not i18n related.

It would be nice to be able to configure grep via its `--exclude=GLOB` paramter from the `config/i18n-tasks.yml` like so:

``` yaml
grep:
  exclude:
    - '*.js*'
    - '*.(le,sa,c)ss'
```

and later in [`I18n::Tasks::BaseTask#find_source_keys`](/glebm/i18n-tasks/blob/master/lib/i18n/tasks/base_task.rb#L22) extend the `run_command 'grep' ...` call.

What do you think?
