### ISSUE TITLE
cannot resolve relative key

### ISSUE THREAD

**Issue by andyw8** [glebm/i18n-tasks#86]
I'm using a relative key `t(".login_success")` in my controller `app/controllers/sessions_controller.rb`.

My localization file in `config/locales/en/session.yml` looks like this:

```
en:
    sessions:
    create:
    login_success: "Login successful"
```

When I run i18n-tasks, it fails with:

```
Error scanning app/controllers/sessions_controller.rb: cannot resolve relative key ".login_success".
       Set relative_roots in config/i18n-tasks.yml (currently ["sessions/create"])
```

I have tried various settings for `relative_roots` but the documentation is not very clear.
