### ISSUE TITLE
Implicit submit button strings marked as unused

### ISSUE THREAD

**Issue by edwardloveall** [glebm/i18n-tasks#98]
I have a form with a submit button that looks like so:

``` ruby
<%= simple_form_for [:employer, @job] do |form| %>
  # ...
  <%= form.button :submit %>
<% end %>
```

and a translation file that looks like so:

``` yml
en:
  helpers:
    submit:
      job:
        create: 'Post job'
        update: 'Change job'
```

`i18n-tasks unused` shows these keys as unused, however because of the way the I18n gem works, they display with these values in the view. I assume it's because i18n scans for yml paths and doesn't do any view rendering. Am I doing it wrong or is this a limitation of this gem?
